"""Learning hub content for stages 8-14."""

from src.learning_hub.models import StageContent
from src.learning_hub.stage14_details import STAGE14_CLASSES

STAGES_08_14: list[StageContent] = [
    {
        "id": 8,
        "title": "Aşama 8 — Agentic Data Analyst",
        "subtitle": "NL→SQL, guardrails, regeneration",
        "summary": "Doğal dil soruyu güvenli read-only SQL'e çevirir; DELETE/DROP engellenir, tenant filter zorunlu.",
        "topics": ["Text-to-SQL", "SQL guardrails", "AST validation", "Human approval", "SQL regeneration"],
        "classes": [
            {
                "path": "src/agents/data_analyst.py",
                "name": "run_data_analyst",
                "purpose": "NL→SQL pipeline: generate, validate, repair, execute.",
                "key_symbols": ["run_data_analyst()", "generate_validated_sql()"],
            },
            {
                "path": "src/security/guardrails.py",
                "name": "validate_sql",
                "purpose": "SELECT-only, forbidden keywords, tenant filter, row limit.",
                "key_symbols": ["validate_sql()", "SqlGuardrailResult"],
            },
            {
                "path": "src/security/sql_correctness.py",
                "name": "sql_correctness",
                "purpose": "Intent detection, canonical SQL fallback, repair.",
                "key_symbols": ["validate_sql_correctness()", "repair_sql()"],
            },
            {
                "path": "src/api/routers/analyst.py",
                "name": "analyst router",
                "purpose": "/v1/analyst/query ve eval endpoint.",
                "key_symbols": ["analyst_query()"],
            },
        ],
        "lab_actions": [
            {
                "id": "analyst-sum",
                "label": "Analyst: Toplam tutar",
                "type": "api_post",
                "endpoint": "/v1/analyst/query",
                "method": "POST",
                "body": {
                    "user_id": "lab-user",
                    "tenant_id": "tenant-a",
                    "question": "What is total amount by tenant",
                },
            },
            {
                "id": "analyst-eval",
                "label": "Analyst Eval",
                "type": "api_get",
                "endpoint": "/v1/analyst/eval",
                "method": "GET",
            },
        ],
        "commands": ["pytest tests/test_sql_guardrails.py -v"],
        "dod": ["DROP/DELETE blocked", "Tenant filter zorunlu", "Regeneration loop"],
        "failure_modes": ["LLM SQL'e kör güven", "Cross-tenant leak"],
        "interview_qa": [
            {
                "question": "Text-to-SQL agent'ı production'a alırken en büyük riskler nelerdir?",
                "answer": "SQL injection, cross-tenant data leak, destructive queries, wrong aggregation → wrong business decision, cost (full table scan).",
                "deep_dive": "Defense: allowlist, read-only DB role, AST parser, row limit, timeout, approval.",
                "red_flags": ["LLM SQL direkt çalıştır"],
                "strong_signals": ["Multi-layer validation", "Read-only role"],
                "tags": ["sql", "risk"],
            },
            {
                "question": "LLM'in ürettiği SQL'i nasıl validate edersin?",
                "answer": "Keyword blocklist, SELECT-only, tenant_id filter check, row LIMIT, AST parse, explain analyze staging'de.",
                "deep_dive": "guardrails.py + sql_correctness.py.",
                "red_flags": ["String contains check only"],
                "strong_signals": ["AST parser", "DB permission last line"],
                "tags": ["sql", "validation"],
            },
            {
                "question": "Read-only data analyst agent için permission model nasıl olur?",
                "answer": "DB read-only user, tenant-scoped views, query timeout, max rows, analyst role RBAC, high-risk query approval.",
                "deep_dive": "tenant_id her sorguda zorunlu.",
                "red_flags": ["Admin DB user"],
                "strong_signals": ["Least privilege DB role"],
                "tags": ["permissions", "sql"],
            },
            {
                "question": "Yanlış analiz sonucu business kararını etkilerse nasıl önlem alırsın?",
                "answer": "Source query görünür, assumptions documented, confidence score, human review threshold, eval on real business questions.",
                "deep_dive": "DataAnalystResult sql + explanation fields.",
                "red_flags": ["Sadece sayı göster"],
                "strong_signals": ["Query transparency", "Eval dataset"],
                "tags": ["business", "analyst"],
            },
            {
                "question": "Agent'ın confidence değerini kullanıcıya göstermeli misin?",
                "answer": "Evet, özellikle düşük confidence'ta — kullanıcı verify edebilir. Ama calibration gerekir; raw logprob yanıltıcı olabilir.",
                "deep_dive": "Eval-based confidence daha güvenilir.",
                "red_flags": ["%99 her zaman"],
                "strong_signals": ["Calibrated confidence", "Abstention"],
                "tags": ["confidence", "ux"],
            },
        ],
        "doc_links": [],
    },
    {
        "id": 9,
        "title": "Aşama 9 — Observability",
        "subtitle": "Traces, metrics, debugging",
        "summary": "Trace session, span timeline, LLM cost metrics ve workflow replay.",
        "topics": ["Distributed tracing", "Metrics collector", "Latency breakdown", "Cost estimate", "Trace replay"],
        "classes": [
            {
                "path": "src/observability/traces.py",
                "name": "TraceSession",
                "purpose": "Span timeline, token summary, trace store replay.",
                "key_symbols": ["start_trace()", "TraceSession.span()", "TraceSummary"],
            },
            {
                "path": "src/observability/metrics.py",
                "name": "MetricsCollector",
                "purpose": "HTTP, LLM, workflow counters ve latency stats.",
                "key_symbols": ["get_metrics()", "record_llm_call()", "record_workflow_run()"],
            },
            {
                "path": "src/api/routers/observability.py",
                "name": "observability router",
                "purpose": "/v1/observability/metrics ve traces/{id}.",
                "key_symbols": ["get_metrics_snapshot()", "get_trace_summary()"],
            },
        ],
        "lab_actions": [
            {
                "id": "obs-metrics",
                "label": "Metrics snapshot",
                "type": "api_get",
                "endpoint": "/v1/observability/metrics",
                "method": "GET",
            },
            {
                "id": "obs-workflow-trace",
                "label": "Workflow + trace",
                "description": "Önce workflow çalıştır, trace_id ile sorgula",
                "type": "api_post",
                "endpoint": "/v1/workflow/run",
                "method": "POST",
                "body": {
                    "user_id": "lab-user",
                    "conversation_id": "lab-trace-1",
                    "message": "50000 TL üzeri işlemler için onay policy nedir?",
                },
            },
        ],
        "commands": ["pytest tests/test_observability.py -v"],
        "dod": ["Timeline spans", "Cost estimate", "Trace replay API"],
        "failure_modes": ["Sadece error log", "Prompt version takipsiz"],
        "interview_qa": [
            {
                "question": "Agent yanlış cevap verdiğinde root cause analysis nasıl yaparsın?",
                "answer": "trace_id replay: prompt version, retrieved chunks, model output, tool args, validation, final answer. Golden case ile karşılaştır.",
                "deep_dive": "GET /v1/observability/traces/{trace_id}",
                "red_flags": ["Tahmin"],
                "strong_signals": ["Replay", "Prompt versioning"],
                "tags": ["rca", "debugging"],
            },
            {
                "question": "LLM latency yüksekse nereden başlarsın?",
                "answer": "Span breakdown: classify vs retrieval vs generation vs tool. p95 per step. Model routing, cache, smaller model for classify.",
                "deep_dive": "trace_summary.timeline latency_ms.",
                "red_flags": ["Genel optimize et"],
                "strong_signals": ["Per-step p95", "Bottleneck first"],
                "tags": ["latency", "performance"],
            },
            {
                "question": "Tool call failure ile model reasoning failure nasıl ayrılır?",
                "answer": "Trace'te span kind: tool vs llm vs classification. Tool failure → external system; LLM failure → parse/timeout.",
                "deep_dive": "span.kind field in timeline.",
                "red_flags": ["Hepsi LLM hatası"],
                "strong_signals": ["Error taxonomy", "Span kinds"],
                "tags": ["debugging", "tools"],
            },
            {
                "question": "Hangi metrikleri dashboard'a koyarsın?",
                "answer": "success rate, p95 latency per step, token cost, tool failure rate, approval rate, block rate, fallback rate, user feedback ratio.",
                "deep_dive": "metrics.snapshot() counters.",
                "red_flags": ["Sadece uptime"],
                "strong_signals": ["Cost per interaction", "Approval SLA"],
                "tags": ["metrics", "dashboard"],
            },
            {
                "question": "Prompt değişikliklerinin etkisini nasıl takip edersin?",
                "answer": "prompt_version tag on trace + eval regression CI + A/B comparison on golden set.",
                "deep_dive": "PROMPT_VERSION env in settings.",
                "red_flags": ["Prompt değişikliği kayıtsız"],
                "strong_signals": ["Versioned prompts", "Eval gate"],
                "tags": ["prompts", "eval"],
            },
        ],
        "doc_links": [],
    },
    {
        "id": 10,
        "title": "Aşama 10 — Evaluation & Guardrails",
        "subtitle": "Golden dataset, regression, injection defense",
        "summary": "Golden dataset eval runner, classification/analyst regression, input guardrails test suite.",
        "topics": [
            "Golden dataset",
            "Regression eval",
            "LLM-as-a-Judge",
            "Input guardrails",
            "PII masking",
            "Test pyramid for LLM",
        ],
        "classes": [
            {
                "path": "src/evals/judge.py",
                "name": "judge_answer",
                "purpose": "Rubric-based LLM-as-a-Judge: groundedness, correctness, completeness, safety.",
                "key_symbols": ["judge_answer()", "pointwise_eval()", "pairwise_eval()"],
            },
            {
                "path": "src/evals/run_evals.py",
                "name": "run_all_evals",
                "purpose": "Classification, analyst, SQL, guardrail eval orchestrator.",
                "key_symbols": ["run_all_evals()", "run_classification_eval()"],
            },
            {
                "path": "src/security/input_guardrails.py",
                "name": "validate_user_input",
                "purpose": "Prompt injection ve data exfiltration detection.",
                "key_symbols": ["validate_user_input()", "detect_prompt_injection()"],
            },
            {
                "path": "src/security/pii.py",
                "name": "mask_pii",
                "purpose": "Email, phone, IBAN maskesi.",
                "key_symbols": ["mask_pii()"],
            },
        ],
        "lab_actions": [
            {
                "id": "eval-classify",
                "label": "Classification Eval",
                "type": "api_get",
                "endpoint": "/v1/classify/eval",
                "method": "GET",
            },
            {
                "id": "eval-judge",
                "label": "LLM-as-a-Judge Eval",
                "type": "api_get",
                "endpoint": "/v1/evals/judge",
                "method": "GET",
            },
            {
                "id": "eval-all",
                "label": "Tüm Eval'ler",
                "type": "api_get",
                "endpoint": "/v1/evals/run",
                "method": "GET",
            },
        ],
        "commands": [
            "pytest tests/test_guardrails.py -v",
            "python -m src.evals.run_evals",
        ],
        "dod": ["10 case golden set", "Eval pass/fail score", "PII mask test"],
        "failure_modes": ["Eval'siz deploy", "Tek katman guardrail"],
        "interview_qa": [
            {
                "question": "Bir agent'ın doğru çalıştığını nasıl test edersin?",
                "answer": "Unit (parser, policy), integration (workflow API), scenario (golden dataset), human eval sample, production monitoring.",
                "deep_dive": "Test pyramid LLM için de geçerli.",
                "red_flags": ["Manuel chat only"],
                "strong_signals": ["Golden regression CI", "Scenario tests"],
                "tags": ["testing", "eval"],
            },
            {
                "question": "LLM output regression test nasıl kurulur?",
                "answer": "Golden JSONL: input → expected intent/risk/approval. Mock LLM deterministic. CI'da run_evals. Threshold score gate.",
                "deep_dive": "classification_golden_dataset.jsonl.",
                "red_flags": ["LLM-as-judge only"],
                "strong_signals": ["Deterministic mock eval", "Versioned dataset"],
                "tags": ["regression", "eval"],
            },
            {
                "question": "Tool çağrısı yapmadan önce hangi validation'ları uygularsın?",
                "answer": "Schema, auth/RBAC, policy decision, idempotency, args guardrail, risk approval.",
                "deep_dive": "validate_tool_arguments + can_execute_tool.",
                "red_flags": ["Direct exec"],
                "strong_signals": ["Multi-gate", "Audit before exec"],
                "tags": ["tools", "validation"],
            },
            {
                "question": "Bankacılık ortamında guardrail tasarımın nasıl olur?",
                "answer": "Defense in depth: input, retrieval filter, output, tool execution. Injection, exfiltration, PII, approval.",
                "deep_dive": "4 katman guardrail diagram mülakatta çiz.",
                "red_flags": ["Tek regex"],
                "strong_signals": ["Layered defense", "Policy engine"],
                "tags": ["guardrails", "banking"],
            },
            {
                "question": "Evaluation dataset'i nasıl oluşturursun?",
                "answer": "Gerçek user queries (anonim), edge cases, injection attempts, ambiguous intents, failure cases. SME review. Versioned JSONL.",
                "deep_dive": "Feedback → golden dataset pipeline.",
                "red_flags": ["10 synthetic only"],
                "strong_signals": ["Production sampling", "SME labeled"],
                "tags": ["dataset", "eval"],
            },
        ],
        "doc_links": [],
    },
    {
        "id": 11,
        "title": "Aşama 11 — Security & Compliance",
        "subtitle": "PII, audit, RBAC, approval",
        "summary": "Banking policy engine, compliance audit events, PII masking, unauthorized tool blocking.",
        "topics": ["PII masking", "Audit trail", "RBAC", "Human approval", "Least privilege", "Defense in depth"],
        "classes": [
            {
                "path": "src/security/audit.py",
                "name": "ComplianceAuditEvent",
                "purpose": "Data minimization ile compliance audit event builder.",
                "key_symbols": ["build_policy_audit_event()", "build_tool_audit_event()"],
            },
            {
                "path": "src/agents/policies.py",
                "name": "Policy engine",
                "purpose": "Role/action matrix; transfer için approval zorunlu.",
                "key_symbols": ["evaluate_tool_permission()", "UserRole"],
            },
            {
                "path": "src/api/routers/security.py",
                "name": "security router",
                "purpose": "/v1/security/audit/recent — son audit kayıtları.",
                "key_symbols": ["list_recent_audit_logs()"],
            },
        ],
        "lab_actions": [
            {
                "id": "audit-recent",
                "label": "Son audit kayıtları",
                "type": "api_get",
                "endpoint": "/v1/security/audit/recent",
                "method": "GET",
            },
            {
                "id": "security-transfer-block",
                "label": "Transfer (onay olmadan)",
                "type": "api_post",
                "endpoint": "/v1/workflow/run",
                "method": "POST",
                "body": {
                    "user_id": "lab-user",
                    "conversation_id": "lab-sec-1",
                    "message": "Hesabımdan 80000 TL transfer et",
                },
            },
        ],
        "commands": ["pytest tests/test_security_policy.py -v"],
        "dod": ["PII masked", "Unauthorized denied", "Approval required"],
        "failure_modes": ["Ham PII audit", "Model güveni"],
        "interview_qa": [
            {
                "question": "Agent'ın hassas müşteri verisini sızdırmasını nasıl engellersin?",
                "answer": "Least privilege, retrieval access control, output filter, PII mask, tool allowlist, audit, DLP scanning.",
                "deep_dive": "input_guardrails data_exfiltration category.",
                "red_flags": ["Model güvenli"],
                "strong_signals": ["Defense in depth", "Access-controlled RAG"],
                "tags": ["data-leak", "security"],
            },
            {
                "question": "Tool access authorization nasıl tasarlanır?",
                "answer": "Policy engine: role × tool × risk matrix. Agent seçer, engine izin verir. DENY/REQUIRE_APPROVAL/ALLOW.",
                "deep_dive": "policies.py can_execute_tool.",
                "red_flags": ["LLM decides auth"],
                "strong_signals": ["Policy as code", "Role matrix"],
                "tags": ["authorization", "tools"],
            },
            {
                "question": "Her tool call için audit log'da ne tutarsın?",
                "answer": "actor, tenant, action, args summary (minimized), approval_id, result, timestamp, trace_id, risk_level.",
                "deep_dive": "ComplianceAuditEvent fields.",
                "red_flags": ["Full customer record"],
                "strong_signals": ["Data minimization", "Trace correlation"],
                "tags": ["audit", "compliance"],
            },
            {
                "question": "PII içeren prompt'ları nasıl yönetirsin?",
                "answer": "Mümkünse prompt'a sokma; gerekiyorsa minimize/mask. Log ve feedback'te mask_pii zorunlu.",
                "deep_dive": "feedback_store message_preview mask.",
                "red_flags": ["Raw PII in CloudWatch"],
                "strong_signals": ["Mask at write", "Retention policy"],
                "tags": ["pii", "compliance"],
            },
            {
                "question": "Bankacılık ortamında autonomous agent'a hangi limitleri koyarsın?",
                "answer": "Irreversible action → human approval. Read-only default. Rate limits. Token budget. No arbitrary code exec. Audit everything.",
                "deep_dive": "Workflow AWAITING_APPROVAL status.",
                "red_flags": ["Full autonomy"],
                "strong_signals": ["Approval gates", "Allowlisted tools"],
                "tags": ["banking", "limits"],
            },
        ],
        "doc_links": [],
    },
    {
        "id": 12,
        "title": "Aşama 12 — AWS Deploy & CI/CD",
        "subtitle": "Docker, Terraform, GitHub Actions",
        "summary": "Containerized FastAPI, ECS/RDS architecture, CI pytest + deploy workflows.",
        "topics": ["Dockerfile", "ECS Fargate", "RDS PostgreSQL", "Secrets Manager", "CI/CD", "Rollback"],
        "classes": [
            {
                "path": "Dockerfile",
                "name": "Container image",
                "purpose": "FastAPI production container + healthcheck.",
                "key_symbols": ["HEALTHCHECK", "uvicorn CMD"],
            },
            {
                "path": "infra/terraform/",
                "name": "Terraform IaC",
                "purpose": "ECS, RDS, ALB, VPC infrastructure.",
                "key_symbols": ["main.tf", "ecs.tf"],
            },
            {
                "path": ".github/workflows/ci.yml",
                "name": "CI workflow",
                "purpose": "pytest + docker build smoke on PR.",
                "key_symbols": ["pytest", "docker build"],
            },
        ],
        "lab_actions": [
            {
                "id": "deploy-health",
                "label": "Healthcheck (local)",
                "type": "api_get",
                "endpoint": "/health",
                "method": "GET",
            },
            {
                "id": "deploy-test",
                "label": "Deploy artifact test",
                "type": "command",
                "command": "pytest tests/test_deploy_artifacts.py -v",
            },
        ],
        "commands": [
            "pytest tests/test_deploy_artifacts.py -v",
            ".\\scripts\\local-test.ps1",
            ".\\scripts\\deploy-compose.ps1  # opsiyonel",
        ],
        "dod": ["Docker build OK", "Healthcheck container", "Architecture doc"],
        "failure_modes": ["Secrets in image", "No rollback plan"],
        "interview_qa": [
            {
                "question": "Bu AI agent sistemini AWS üzerinde nasıl deploy edersin?",
                "answer": "ALB → ECS Fargate (FastAPI) → RDS PostgreSQL private subnet. Secrets Manager. CloudWatch. CI/CD ECR push + terraform apply.",
                "deep_dive": "docs/aws_architecture.md diagram.",
                "red_flags": ["EC2 manual SSH"],
                "strong_signals": ["IaC", "Private subnet RDS"],
                "tags": ["aws", "deploy"],
            },
            {
                "question": "FastAPI servisini ECS üzerinde nasıl çalıştırırsın?",
                "answer": "Docker image → ECR → task definition → service → ALB target group. Health check /health. Auto-scaling on CPU/latency.",
                "deep_dive": "Dockerfile HEALTHCHECK.",
                "red_flags": ["Single EC2 no orchestration"],
                "strong_signals": ["Fargate", "Health-based routing"],
                "tags": ["ecs", "fastapi"],
            },
            {
                "question": "Secrets ve API key yönetimini nasıl yaparsın?",
                "answer": "Secrets Manager / Parameter Store. ECS task env from secrets. Rotation plan. Never in git or image.",
                "deep_dive": ".env local only; gitignored.",
                "red_flags": [".env in Docker image"],
                "strong_signals": ["Secrets Manager", "Rotation"],
                "tags": ["secrets", "security"],
            },
            {
                "question": "CloudWatch'ta hangi metrikleri takip edersin?",
                "answer": "ECS CPU/memory, ALB 5xx, p95 latency, custom LLM cost, error rate, log insights for trace_id.",
                "deep_dive": "observability metrics → CloudWatch exporter.",
                "red_flags": ["Logs only no metrics"],
                "strong_signals": ["Alarms", "Dashboard per service"],
                "tags": ["cloudwatch", "monitoring"],
            },
            {
                "question": "Production incident olduğunda nasıl rollback yaparsın?",
                "answer": "1) trace/log RCA 2) previous image tag deploy 3) terraform/ecs update 4) desired_count=0 if critical.",
                "deep_dive": "docs/aws_architecture.md § Incident.",
                "red_flags": ["Fix forward only"],
                "strong_signals": ["Versioned images", "Rollback runbook"],
                "tags": ["incident", "rollback"],
            },
        ],
        "doc_links": ["docs/aws_architecture.md", "docs/deploy_workflow.md"],
    },
    {
        "id": 13,
        "title": "Aşama 13 — Frontend & AI UX",
        "subtitle": "Streaming, approval UI, feedback",
        "summary": "Demo UI: workflow/chat modları, onay modalı, trace panel, feedback collection.",
        "topics": ["SSE streaming", "Tool step visibility", "Approval modal", "Feedback loop", "Error/retry UX"],
        "classes": [
            {
                "path": "frontend/app.js",
                "name": "Demo UI",
                "purpose": "Workflow + SSE chat + approval + feedback client logic.",
                "key_symbols": ["runWorkflow()", "streamChat()", "submitFeedback()"],
            },
            {
                "path": "frontend/src/client.ts",
                "name": "AgenticApiClient",
                "purpose": "Type-safe TypeScript API client referansı.",
                "key_symbols": ["AgenticApiClient"],
            },
            {
                "path": "src/api/routers/feedback.py",
                "name": "feedback API",
                "purpose": "POST /v1/feedback — trace_id ile eval bağlantısı.",
                "key_symbols": ["submit_feedback()"],
            },
            {
                "path": "src/evals/feedback_store.py",
                "name": "feedback store",
                "purpose": "JSONL feedback persistence, PII masked.",
                "key_symbols": ["append_feedback()"],
            },
        ],
        "lab_actions": [
            {
                "id": "ui-demo",
                "label": "Demo UI aç",
                "type": "navigate",
                "navigate": "/ui/",
                "description": "Workflow ve Chat Stream modlarını dene",
            },
            {
                "id": "feedback-post",
                "label": "Feedback gönder",
                "type": "api_post",
                "endpoint": "/v1/feedback",
                "method": "POST",
                "body": {
                    "user_id": "lab-user",
                    "conversation_id": "lab-conv",
                    "rating": "positive",
                    "message_preview": "Policy cevabı faydalıydı",
                },
            },
        ],
        "commands": ["pytest tests/test_feedback.py -v"],
        "dod": ["Streaming UI", "Approval modal", "Feedback trace_id"],
        "failure_modes": ["CoT gösterme", "Frontend'e policy güvenme"],
        "interview_qa": [
            {
                "question": "Agent response streaming frontend'de nasıl gösterilir?",
                "answer": "SSE fetch + ReadableStream reader; her data: chunk'ı assistant balonuna append; scroll; disable input during stream.",
                "deep_dive": "frontend/app.js streamChat().",
                "red_flags": ["Full response wait"],
                "strong_signals": ["Progressive render", "Retry on fail"],
                "tags": ["streaming", "frontend"],
            },
            {
                "question": "Tool call adımlarını kullanıcıya göstermeli misin?",
                "answer": "Evet ama domain-friendly: 'Bilgi aranıyor' not raw JSON. Banking'de güven verir, CoT sızdırmaz.",
                "deep_dive": "STEP_LABELS in app.js.",
                "red_flags": ["Raw tool JSON"],
                "strong_signals": ["Domain labels", "Progress steps"],
                "tags": ["ux", "tools"],
            },
            {
                "question": "Human-in-the-loop approval ekranı nasıl tasarlanır?",
                "answer": "Summary + risk + tool name + approval_id + confirm/cancel. Modal + side card. Resume ile devam.",
                "deep_dive": "approval-modal in index.html.",
                "red_flags": ["Tek tık auto-approve"],
                "strong_signals": ["Double confirm", "Audit id visible"],
                "tags": ["approval", "ux"],
            },
            {
                "question": "Frontend'den gelen prompt injection riskleri nasıl azaltılır?",
                "answer": "Backend guardrails; frontend untrusted. No system prompt in client. Policy server-side only.",
                "deep_dive": "validate_user_input on every endpoint.",
                "red_flags": ["Client-side filter only"],
                "strong_signals": ["Backend validation", "No secrets in JS"],
                "tags": ["injection", "frontend"],
            },
            {
                "question": "Kullanıcı feedback'i evaluation pipeline'a nasıl bağlanır?",
                "answer": "POST /v1/feedback with trace_id → feedback.jsonl → negative cases → golden dataset → regression.",
                "deep_dive": "docs/ai_ux_notes.md feedback section.",
                "red_flags": ["Feedback kaybolur"],
                "strong_signals": ["trace_id link", "PII masked store"],
                "tags": ["feedback", "eval"],
            },
        ],
        "doc_links": ["docs/ai_ux_notes.md"],
    },
    {
        "id": 14,
        "title": "Aşama 14 — System Design Case Study",
        "subtitle": "End-to-end banking assistant",
        "summary": "Tüm modüller tek workflow'da birleşir. E2E scenarios ve production readiness checklist.",
        "topics": ["E2E architecture", "Failure modes", "MVP scope", "Business impact", "Production checklist"],
        "classes": STAGE14_CLASSES,
        "lab_actions": [
            {
                "id": "case-study-demo",
                "label": "E2E Case Study Demo",
                "type": "command",
                "command": "python -m src.case_study.run_demo",
            },
            {
                "id": "case-study-wf",
                "label": "Full workflow E2E",
                "type": "api_post",
                "endpoint": "/v1/workflow/run",
                "method": "POST",
                "body": {
                    "user_id": "employee-1",
                    "conversation_id": "case-study-1",
                    "message": "Şifre sıfırlama policy nedir?",
                },
            },
        ],
        "commands": [
            "pytest tests/test_case_study_integration.py -v",
            "python -m src.case_study.run_demo",
        ],
        "dod": ["4 E2E scenario pass", "System design doc", "Production checklist"],
        "failure_modes": ["Prompt+vector only design", "No business metrics"],
        "interview_qa": [
            {
                "question": "Kurum çalışanları için internal banking knowledge assistant uçtan uca nasıl kurarsın?",
                "answer": "Problem → ingestion+access control → FastAPI workflow → hybrid RAG → policy-guarded tools → approval → audit → eval → observability → AWS deploy. MVP: policy lookup + guarded transfer.",
                "deep_dive": "docs/system_design_case_study.md full 11-section skeleton.",
                "red_flags": ["Sadece ChatGPT wrapper"],
                "strong_signals": ["MVP scope", "Security layers"],
                "tags": ["system-design", "e2e"],
            },
            {
                "question": "Bu sistemde en kritik failure mode'lar nelerdir?",
                "answer": "Hallucinated policy, prompt injection, unauthorized transfer, LLM timeout, stale docs, eval drift, PII leak.",
                "deep_dive": "Failure mode table in system_design_case_study.md.",
                "red_flags": ["Failure mode yok"],
                "strong_signals": ["Mitigation per failure"],
                "tags": ["failure-modes"],
            },
            {
                "question": "İlk MVP'de neyi dahil eder, neyi sonraya bırakırsın?",
                "answer": "MVP: workflow, guardrails, approval, audit, eval, demo UI. Sonra: hybrid search, real ingestion, multi-agent, dashboard.",
                "deep_dive": "production_readiness_checklist.md Go/No-Go.",
                "red_flags": ["Her şey day 1"],
                "strong_signals": ["Phased rollout"],
                "tags": ["mvp", "scope"],
            },
            {
                "question": "Production readiness checklist'in ne olur?",
                "answer": "Security (guardrails, RBAC, PII), eval regression, healthcheck, secrets, observability, rollback, backup, pen test.",
                "deep_dive": "docs/production_readiness_checklist.md 44 items.",
                "red_flags": ["Checklist yok"],
                "strong_signals": ["Mapped to code", "Go/No-Go"],
                "tags": ["production", "checklist"],
            },
            {
                "question": "Business impact'i nasıl ölçersin?",
                "answer": "Resolution time, deflection rate, accuracy (eval), adoption, cost/interaction. Trace + feedback kaynakları.",
                "deep_dive": "Impact metrics table stage 14 doc.",
                "red_flags": ["Impact ölçülmez"],
                "strong_signals": ["Measurable KPIs"],
                "tags": ["business", "impact"],
            },
        ],
        "doc_links": [
            "docs/system_design_case_study.md",
            "docs/production_readiness_checklist.md",
        ],
    },
]
